version: '2'

services:

  mongo:
    image: mongo:4.4.6
    restart: always
    ports:
      - 9000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - ./mongo_data:/data/db
    networks:
      - backend
networks:
  backend:
    external:
      name: proxy
